# -*- coding: utf-8 -*-
"""Score interdisciplinarité.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Afh23D91zAe-AvV7UGUu3XiQvfR-oO7p
"""

"""
Analyse bibliométrique HAL — Score d'interdisciplinarité des revues
====================================================================
Étape 1 : Récupérer les revues avec ≥ 100 articles dans la collection (structId)
Étape 2 : Pour chaque revue, requêter HAL global pour la distribution des domaines
Étape 3 : Calculer le score de Shannon normalisé
Étape 4 : Classer les revues et calculer le % de publications "interdisciplinaires"
"""

import requests
import math
import time
import json
from collections import defaultdict

# ── Paramètres ────────────────────────────────────────────────────────────────

STRUCT_ID       = 7550          # Identifiant de ta structure dans HAL
MIN_ARTICLES    = 50           # Seuil pour l'étape 1 (revues de ta collection)
INTER_THRESHOLD = 0.4           # Seuil Shannon normalisé → revue "interdisciplinaire"
PAUSE           = 0.2           # Pause entre requêtes (secondes) — respecte l'API HAL

HAL_API = "https://api.archives-ouvertes.fr/search/"

# ── Étape 1 : Revues avec ≥ MIN_ARTICLES dans la collection ───────────────────

def get_journals_from_collection(struct_id, min_count):
    """Retourne {journalId: (journalTitle, count)} pour les revues >= min_count articles."""
    print(f"\n[Étape 1] Récupération des revues (structId={struct_id}, min={min_count} articles)...")

    params = {
        "q": f"structId_i:{struct_id}",
        "fq": "docType_s:ART",
        "rows": 0,
        "wt": "json",
        "facet": "true",
        "facet.field": "journalId_i",
        "facet.limit": 5000,
        "facet.mincount": min_count,
    }

    r = requests.get(HAL_API, params=params)
    r.raise_for_status()
    data = r.json()

    raw = data["facet_counts"]["facet_fields"]["journalId_i"]
    # Solr retourne [id, count, id, count, ...]
    journals = {}
    for i in range(0, len(raw), 2):
        jid, count = raw[i], raw[i+1]
        if count >= min_count:
            journals[jid] = count

    print(f"  → {len(journals)} revues trouvées avec ≥ {min_count} articles")
    return journals


# ── Étape 2 : Distribution des domaines sur HAL global ────────────────────────

def get_domain_distribution(journal_id):
    """Retourne {domain: count} pour une revue sur l'ensemble de HAL."""
    params = {
        "q": f"journalId_i:{journal_id}",
        "rows": 1,
        "wt": "json",
        "fl": "journalTitle_s",
        "facet": "true",
        "facet.field": "level0_domain_s",
        "facet.mincount": 1,     # ← supprime les zéros
    }

    r = requests.get(HAL_API, params=params)
    r.raise_for_status()
    data = r.json()

    docs = data["response"]["docs"]
    title = docs[0].get("journalTitle_s", "?") if docs else "?"

    raw = data["facet_counts"]["facet_fields"]["level0_domain_s"]
    total_docs = data["response"]["numFound"]

    distribution = {}
    for i in range(0, len(raw), 2):
        domain, count = raw[i], raw[i+1]
        if domain.strip():  # ignore les chaînes vides résiduelles
            distribution[domain] = count

    distribution = {d: c for d, c in distribution.items() if c >= 3}

    return distribution, total_docs, title


# ── Étape 3 : Score de Shannon normalisé ──────────────────────────────────────
def shannon_normalized(distribution):
    """
    Calcule l'entropie de Shannon normalisée ∈ [0, 1].
    0 = revue mono-disciplinaire pure
    1 = toutes les disciplines équiréparties
    """
    counts = [v for v in distribution.values() if v > 0]
    if not counts:
        return 0.0

    total = sum(counts)
    n = len(counts)
    if n == 1:
        return 0.0

    entropy = -sum((c / total) * math.log(c / total) for c in counts)
    max_entropy = math.log(n)   # entropie maximale si distribution uniforme

    return entropy / max_entropy


# ── Pipeline principale ────────────────────────────────────────────────────────

def run(struct_id=STRUCT_ID, min_articles=MIN_ARTICLES, threshold=INTER_THRESHOLD):

    # 1. Revues de la collection
    journals_counts = get_journals_from_collection(struct_id, min_articles)

    # 2 + 3. Pour chaque revue, domaines HAL global + score Shannon
    print(f"\n[Étape 2-3] Requêtes HAL global + calcul Shannon pour {len(journals_counts)} revues...")

    results = []
    errors  = []

    for idx, (jid, local_count) in enumerate(journals_counts.items(), 1):
        try:
            distribution, total_hal, title = get_domain_distribution(jid)
            score = shannon_normalized(distribution)

            # Domaine majoritaire (pour info)
            top_domain = max(distribution, key=distribution.get) if distribution else "?"

            results.append({
                "journalId":     jid,
                "journalTitle":  title,
                "local_count":   local_count,   # articles dans ta collection
                "hal_total":     total_hal,      # articles dans HAL global
                "n_domains":     len(distribution),
                "top_domain":    top_domain,
                "shannon_norm":  round(score, 4),
                "interdisciplinary": score >= threshold,
                "domain_dist":   distribution,
            })

            print(f"  [{idx:>3}/{len(journals_counts)}] {title:<60} |  Id={ jid} | "
      f"HAL={total_hal:>6} | dom={len(distribution):>2} | "
      f"Shannon={score:.3f} | {'✓ INTER' if score >= threshold else '  mono'}")

        except Exception as e:
            print(f"  [ERREUR] journalId={jid} : {e}")
            errors.append(jid)

        time.sleep(PAUSE)

    # 4. Calcul du % de publications interdisciplinaires dans la collection
    print(f"\n[Étape 4] Calcul du pourcentage...")

    total_local_articles    = sum(r["local_count"] for r in results)
    inter_local_articles    = sum(r["local_count"] for r in results if r["interdisciplinary"])
    pct_inter               = (inter_local_articles / total_local_articles * 100) if total_local_articles else 0

    print(f"\n{'='*60}")
    print(f"  Revues analysées          : {len(results)}")
    print(f"  Revues interdisciplinaires: {sum(1 for r in results if r['interdisciplinary'])} "
          f"(seuil Shannon ≥ {threshold})")
    print(f"  Articles dans la collection (revues analysées) : {total_local_articles}")
    print(f"  dont dans revues interdisciplinaires           : {inter_local_articles}")
    print(f"  → Pourcentage interdisciplinaire               : {pct_inter:.1f}%")
    if errors:
        print(f"\n  Erreurs sur {len(errors)} revues : {errors}")
    print(f"{'='*60}\n")

    # Export JSON pour réutilisation
    output = {
        "params": {
            "struct_id": struct_id,
            "min_articles": min_articles,
            "threshold": threshold,
        },
        "summary": {
            "n_journals": len(results),
            "n_interdisciplinary": sum(1 for r in results if r["interdisciplinary"]),
            "total_local_articles": total_local_articles,
            "inter_local_articles": inter_local_articles,
            "pct_interdisciplinary": round(pct_inter, 2),
        },
        "journals": sorted(results, key=lambda x: x["shannon_norm"], reverse=True),
    }

    with open("hal_results.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print("  Résultats exportés dans hal_results.json")

    return output


# ── Point d'entrée ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    run()