# -*- coding: utf-8 -*-
"""Script curation v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaViWtcKECsZMmowcf2b9ZjPkpW6DQkm
"""

import re
import requests
import time
import json

#dictionnaire doctypes

DOCTYPE_LABELS = {
    'ART': 'Article',
    'COUV': 'Chapitre',
    'OUV': 'Ouvrage',
    'NOTICE': 'Notice de dictionnaire',
    'COMM': 'Communication',
    'UNDEFINED': 'Working Paper',
    'IMG': 'Image',
    'THESE': 'Thèse',
    'HDR': 'HDR',
    'POSTER': 'Poster',
    'REPORT': 'Rapport',
}

# ============================================================================
# PARTIE 1 : EXTRACTION DES NOTICES DEPUIS LE FICHIER TEXTE
# ============================================================================

def extract_notices(file_path):
    """
    Extrait les notices avec leur numéro, citation et halId depuis le fichier texte
    """
    notices = []

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Découper par les lignes de séparation
    raw_notices = content.split('-----------------------------------------------------------------------------')

    for raw in raw_notices:
        if not raw.strip():
            continue

        # Extraire le numéro
        num_match = re.search(r'\[# (\d+)\]', raw)
        num = num_match.group(1) if num_match else None

        # Extraire le halId
        halid_match = re.search(r'\u27E8(hal[a-z]*-\d+(?:v\d+)?)\u27E9', raw)
        hal_id = halid_match.group(1) if halid_match else None

        # Extraire l'URL (avec balises HTML)
        url_match = re.search(r'URL : <a href="(https://[^"]+)">', raw)
        url = url_match.group(1) if url_match else None

        if hal_id:
            # Convertir halId en docId
            docid = re.sub(r'^hal[a-z]*-0*', '', hal_id)
            docid = re.sub(r'v\d+$', '', docid)

            notices.append({
                'numero': num,
                'hal_id': hal_id,
                'docid': docid,
                'url': url,
                'raw': raw.strip()
            })

    return notices


# ============================================================================
# PARTIE 2 : REQUÊTES API HAL
# ============================================================================

def fetch_docid_from_page(url):
    """
    Récupère le docId depuis la page HTML HAL
    Cherche le pattern : data-docid="XXXXXX"
    """
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()

        # Chercher le pattern data-docid="XXXXXX"
        match = re.search(r'data-docid="(\d+)"', response.text)
        if match:
            return match.group(1)
        else:
            return None
    except Exception as e:
        print(f"  ⚠️  Erreur lors de la récupération de la page: {e}")
        return None


def fetch_hal_metadata(notice):
    """
    Récupère les métadonnées HAL pour une notice
    Avec fallback sur la page HTML si le docid calculé ne fonctionne pas
    """
    docid = notice['docid']
    url_api = f"https://api.archives-ouvertes.fr/search?q=docid:{docid}&fl=*&wt=json"

    try:
        response = requests.get(url_api, timeout=10)
        response.raise_for_status()
        data = response.json()

        if data.get('response', {}).get('numFound', 0) > 0:
            return data['response']['docs'][0]
        else:
            # Fallback: aller chercher le docId sur la page HTML
            print(f"  ⚠️  DocId calculé ({docid}) non trouvé, tentative via la page HTML...")
            real_docid = fetch_docid_from_page(notice['url'])

            if real_docid and real_docid != docid:
                print(f"  ✓ DocId réel trouvé: {real_docid}")
                url_api_fallback = f"https://api.archives-ouvertes.fr/search?q=docid:{real_docid}&fl=*&wt=json"

                response2 = requests.get(url_api_fallback, timeout=10)
                response2.raise_for_status()
                data2 = response2.json()

                if data2.get('response', {}).get('numFound', 0) > 0:
                    return data2['response']['docs'][0]

            return None

    except Exception as e:
        print(f"  ⚠️  Erreur API: {e}")
        return None

def count_authors_without_affiliation(metadata):
    """
    Compte le nombre d'auteurs sans affiliation
    """
    if not metadata:
        return None, None

    # Liste de tous les authId
    all_authors = metadata.get('authIdFormPerson_s', [])

    # Liste des authId qui ont une affiliation
    struct_with_auth = metadata.get('structHasAlphaAuthId_fs', [])

    # Extraire les authId depuis structHasAlphaAuthId_fs
    authors_with_affiliation = set()
    for entry in struct_with_auth:
        # Format: "..._JoinSep_AUTHID_FacetSep_NOM"
        # On cherche le pattern entre _JoinSep_ et _FacetSep_
        match = re.search(r'_JoinSep_([^_]+)_FacetSep_', entry)
        if match:
            authors_with_affiliation.add(match.group(1))

    # Compter ceux sans affiliation
    authors_without_affiliation = []
    for auth_id in all_authors:
        if auth_id not in authors_with_affiliation:
            authors_without_affiliation.append(auth_id)

    total_authors = len(all_authors)
    nb_without_affiliation = len(authors_without_affiliation)

    return nb_without_affiliation, total_authors

def analyze_notices(notices):
    """
    Récupère les métadonnées pour toutes les notices
    """
    results = []

    for i, notice in enumerate(notices, 1):
        print(f"[{i}/{len(notices)}] Analyse de {notice['hal_id']}...")

        metadata = fetch_hal_metadata(notice)  # On passe maintenant la notice complète

        if metadata:
            results.append({
                'notice': notice,
                'metadata': metadata
            })
        else:
            print(f"  ❌ Notice non trouvée même après fallback")
            results.append({
                'notice': notice,
                'metadata': None
            })

        # Pause pour ne pas surcharger l'API
        time.sleep(0.3)  # Un peu plus long car on fait potentiellement 2 requêtes

    return results

def search_duplicates(metadata, hal_id_base):
    """
    Cherche des doublons potentiels pour une notice
    (code adapté du bookmarklet)
    """
    if not metadata:
        return []

    titles = metadata.get('title_s', [])
    if not isinstance(titles, list):
        titles = [titles] if titles else []

    doi = metadata.get('doiId_s')
    if isinstance(doi, list):
        doi = doi[0] if doi else None

    # Construction de la requête
    qParts = []
    if doi:
        qParts.append(f'doiId_s:"{doi}"')

    # Ajouter une partie de requête pour CHAQUE titre
    for title in titles:
        if title:
            mots = re.sub(r'[()":!?,;\'\'-]', '', title)
            mots = ' '.join(mots.split()[:12])
            if mots:
                qParts.append(f'title_t:({mots})')

    if not qParts:
        return []

    query = ' OR '.join(qParts)
    url = f"https://api.archives-ouvertes.fr/search?q={requests.utils.quote(query)}&fl=halId_s,title_s,doiId_s&wt=json&rows=50"

    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()

        if not data.get('response', {}).get('docs'):
            return []

        # Filtrer les résultats
        duplicates = []
        for doc in data['response']['docs']:
            doc_halid = doc.get('halId_s', '')
            doc_halid_base = re.sub(r'v\d+$', '', doc_halid)
            doc_doi = doc.get('doiId_s')
            if isinstance(doc_doi, list):
                doc_doi = doc_doi[0] if doc_doi else None

            # Exclure la notice elle-même
            if doc_halid_base == hal_id_base:
                continue

            # Si les deux ont un DOI, ils doivent matcher
            if doi and doc_doi and doc_doi != doi:
                continue

            duplicates.append({
                'halId': doc_halid,
                'title': doc.get('title_s', [''])[0] if isinstance(doc.get('title_s'), list) else doc.get('title_s', ''),
                'doi': doc_doi
            })

        return duplicates

    except Exception as e:
        print(f"  ⚠️  Erreur recherche doublons: {e}")
        return []


# ============================================================================
# PARTIE 3 : FLAGGING ET ANALYSE
# ============================================================================

def flag_notice(metadata, notice):
    """
    Analyse une notice et retourne les flags/infos pertinentes
    """
    if not metadata:
        return ['❌ Notice non trouvée dans l\'API'], {'doc_type': 'UNKNOWN'}

    flags = []
    info = {}

    # Récupérer le type de document
    doc_type = metadata.get('docType_s', 'UNKNOWN')
    doc_type_label = DOCTYPE_LABELS.get(doc_type, doc_type)  # Si pas trouvé, garde le code
    info['doc_type'] = doc_type_label

    # IMPORTANT: Garde le code original pour les conditions
    doc_type_code = doc_type

    # Flag 1: Article sans DOI (si publié et pas en droit)
    if doc_type_code == 'ART':
        doi = metadata.get('doiId_s')
        in_press = metadata.get('inPress_bool', False)
        domains = metadata.get('domain_s', [])

        # Vérifier si c'est du droit
        is_law = False
        if isinstance(domains, list):
            is_law = any('shs.droit' in domain for domain in domains)
        elif isinstance(domains, str):
            is_law = 'shs.droit' in domains

        # Stocker l'info du DOI
        info['doi'] = doi if doi else 'ABSENT'

        # Flag seulement si : pas de DOI + publié (not in_press) + pas du droit
        if not doi and not in_press and not is_law:
            flags.append('⚠️ Article sans DOI')

    # Flag 2: Éditeur scientifique pour les ouvrages (COUV)
    if doc_type == 'COUV':
        scientific_editor = metadata.get('scientificEditor_s')
        if scientific_editor:
            info['scientific_editor'] = scientific_editor
        else:
            info['scientific_editor'] = 'Non renseigné'

    # Flag 3: Revue invalide
    journal_valid = metadata.get('journalValid_s')
    if journal_valid == 'INCOMING':
        flags.append('⚠️ Revue invalide (INCOMING)')

    # Flag 4: Auteurs sans affiliation
    nb_without, total = count_authors_without_affiliation(metadata)
    if nb_without and nb_without > 0:
        info['auteurs_sans_affiliation'] = f"{nb_without}/{total}"
        flags.append(f'⚠️ {nb_without} auteur(s) sans affiliation sur {total}')

    # Flag 5: Structures françaises non validées
    struct_valid = metadata.get('structValid_s', [])
    struct_country = metadata.get('structCountry_s', [])

    # S'assurer que ce sont des listes
    if not isinstance(struct_valid, list):
        struct_valid = [struct_valid] if struct_valid else []
    if not isinstance(struct_country, list):
        struct_country = [struct_country] if struct_country else []

    # Vérifier s'il y a des structures françaises non validées
    french_invalid_structs = []
    for i, (valid, country) in enumerate(zip(struct_valid, struct_country)):
        if country == 'fr' and valid == 'INCOMING':
            french_invalid_structs.append(i)

    if french_invalid_structs:
        nb_invalid = len(french_invalid_structs)
        flags.append(f'⚠️ {nb_invalid} structure(s) française(s) non validée(s)')
        info['structures_invalides'] = nb_invalid

# Flag 6: Doublons potentiels
    hal_id_base = re.sub(r'v\d+$', '', notice['hal_id'])
    duplicates = search_duplicates(metadata, hal_id_base)

    # Prepare title for display, ensuring it's a string
    display_title = ""
    titles_from_metadata = metadata.get('title_s')
    if isinstance(titles_from_metadata, list) and titles_from_metadata:
        display_title = titles_from_metadata[0]
    elif isinstance(titles_from_metadata, str):
        display_title = titles_from_metadata

    if duplicates:
        info['nb_doublons'] = len(duplicates)
        info['titre_notice'] = display_title # Add the title to info
        flags.append(f'⚠️ {len(duplicates)} doublon(s) potentiel(s)') # Removed empty '()'

    return flags, info


def generate_report(results):
    """
    Génère un rapport lisible des notices analysées
    """
    print("\n" + "="*80)
    print("RAPPORT D'ANALYSE DES NOTICES HAL")
    print("="*80 + "\n")

    for i, result in enumerate(results, 1):
        notice = result['notice']
        metadata = result['metadata']

        flags, info = flag_notice(metadata, notice)

        # Affichage de base
        print(f"[#{notice['numero']}] {notice['hal_id']}")
        print(f"  Type: {info.get('doc_type', 'UNKNOWN')}")

        # Infos spécifiques selon le type
        if 'doi' in info:
            print(f"  DOI: {info['doi']}")

        if 'scientific_editor' in info:
            print(f" ✒️ Éditeur scientifique: {info['scientific_editor']}")

        if 'auteurs_sans_affiliation' in info:
            print(f"  Auteurs sans affiliation: {info['auteurs_sans_affiliation']}")

        if 'nb_doublons' in info:
            print(f"  Doublons potentiels: {info['nb_doublons']}, {info['titre_notice']}")

        # Affichage des flags
        if flags:
            print(f" 🔴 PROBLÈMES DÉTECTÉS:")
            for flag in flags:
                print(f"     {flag}")
        else:
            print(f"  ✅ Aucun problème détecté")

        print(f"  URL: {notice['url']}")
        print()

# ============================================================================
# PARTIE 4 : SCRIPT PRINCIPAL
# ============================================================================

if __name__ == "__main__":
    from google.colab import files

    print("📤 Veuillez uploader vos fichiers (vous pouvez en sélectionner plusieurs)...")
    uploaded = files.upload()

    all_notices = []

    # Traiter chaque fichier uploadé
    for filename in uploaded.keys():
        print(f"\n📄 Traitement de {filename}...")
        notices = extract_notices(filename)
        all_notices.extend(notices)
        print(f"  ✅ {len(notices)} notices extraites")

    print(f"\n📋 TOTAL : {len(all_notices)} notices à analyser\n")

    # 2. Récupérer les métadonnées depuis l'API
    print("🔍 Analyse des notices via l'API HAL...\n")
    results = analyze_notices(all_notices)

    # 3. Générer le rapport
    generate_report(results)